# Generated by Django 5.1.3 on 2024-12-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalPark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('picture', models.ImageField(max_length=255, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('established', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('elevation', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('difficultyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='store.difficultytype')),
                ('nationalPark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='store.nationalpark')),
            ],
        ),
    ]
